export enum QueueJobs {
  AUTO_CASHOUT = 'AUTO_CASHOUT',
  HILO_SETTLE_BET = 'HILO_SETTLE_BET',
  MINES_SETTLE_BET = 'MINES_SETTLE_BET',
  BOTTLESMASH_SETTLE_BET = 'BOTTLESMASH_SETTLE_BET',
  OVERANDOUT_SETTLE_BET = 'OVERANDOUT_SETTLE_BET',
}
